name = "TF47 Mod"
modname = "taskforce47_client_mod"
prefix = "TF47"
author = "TF47 Development Team"
files = [
	"mod.cpp",
	"meta.cpp",
	"*.paa"
]
include = [
    "./include"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip tf47_mod_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version= "{{git \"id 8\"}}"